### ISSUE TITLE
Allow it to compile on MacOS

### ISSUE THREAD

**Issue by rokicki** [sebastianotronto/nissy#2]
To compile on MacOS, drop the -static from the Makefile.  Generally, static compilation even on linux is increasingly frowned upon and less supported.

**Comment by sebastianotronto** [comment]
I did not know that. Originally I had -static only for Windows (necessary for pthreads). Playing around with httpd + fastcgi on OpenBSD I noticed that I needed static compilation for that too. I'll make a new make target for that when needed.
