### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by GuidoDipietro** [sebastianotronto/nissy#3]
Hey, it seems that the `zip` link for the tables is broken (https://math.uni.lu/tronto/nissy/nissy-tables-2.0.zip). Or some 
configuration is missing. I get the following message:

### You don't have permission to access this resource.

Thanks for this tool btw, it is so good

**Comment by sebastianotronto** [comment]
Thanks for bringing this up, I had some problems uploading the file. I don't know if I can fix it before next week. In the meantime you can use the .tar.gz file or download the (uncompressed) files from https://math.uni.lu/tronto/nissy/tables

**Comment by sebastianotronto** [comment]
It should be fixed now.
