### ISSUE TITLE
[Feature Request] Specify move set used to solve

### ISSUE THREAD

**Issue by LeviGibson** [sebastianotronto/nissy#5]
For the solve command, allow the user to specify the move set the solver is allowed to use. When trying to find optimal corner solutions for bad DRs, Nissy often comes up with corner solutions that break the DR, and implementing this feature would give users more fine control over that. It would also dramatically reduce the width of the search tree. 

This would also be really useful in other cases. Say I have an DR with a 2x2x2 block, and I want to see if there is a good intuitive blockbuilding finish from that 2x2x2. I can set the the moveset to [U U' U2 R2 F2] and see the best solution (assuming the block is in BL). This would be a lot easier than sifting through sub-optimal solutions looking to see if any of them preserve the 2x2x2.

**Comment by sebastianotronto** [comment]
This is interesting, but doing it very generally will require some work. I added it to my to-do list.

For DR corners, the feature was already there in version 1 iirc, but I did not port it to version 2. Now I am busy re-structuring the whole optimal solver part (as usual...), but I can add it quite easily to the current stable version and make a 2.0.4 release.

**Comment by sebastianotronto** [comment]
Implemented new step `corners-dr` , will be available in 2.0.4 (probably in a few days).
Also notice that the repository has been moved to [nissy-classic](https://github.com/sebastianotronto/nissy-classic), check the readme of this repo for more info.
